source:
  type: local_files
  config:
    path: ./data/vectorflow_intro.txt

chunker:
  type: recursive_character
  config:
    chunk_size: 150
    chunk_overlap: 30

embedder:
  type: sentence_transformer
  config:
    model_name: "jhgan/ko-sbert-nli"

sink:
  type: lancedb
  config:
    uri: "./lancedb_final"
    table_name: "my_documents"